add pdfs
csunibo/strategia-aziendale pull request #14
Opened 2024-05-20 18:17 UTC by Flecart

2024-05-20 18:46 UTC, foxyseta requested changes
Chiederesti a chi ti ha dato queste risorse se

2024-05-20 18:46 UTC, foxyseta commented on prove/orale-2024-testo.pdf
Qui aggiungerei `-simulazione` o `-esempi`, non trattandosi di un esame vero.

2024-05-20 18:46 UTC, foxyseta commented on prove/scritto-2024-soluzione.pdf
Chiederesti a chi ti ha dato questi file se ci siano date più specifiche per `prove/scritto-2024-1-testo.pdf` e `prove/scritto-2024-soluzione.pdf`? In caso negativo, quantomento rinominerei `prove/scritto-2024-soluzione.pdf` in `prove/scritto-2024-1-soluzione.pdf` affinché l'elenco dei file si comporti bene rispetto all'ordine meccanografico di statik.

2024-05-20 20:02 UTC, Flecart commented on prove/scritto-2024-soluzione.pdf
dovrebbero essere di oggi!

2024-05-20 21:42 UTC, foxyseta approved these changes

2024-05-20 21:43 UTC, foxyseta commented
Mi sembra perfetto. La accettiamo?

2024-05-21 08:42 UTC, ali-benny commented
> Mi sembra perfetto. La accettiamo?

@ngljcb

2024-05-21 10:10 UTC, ngljcb approved these changes

2024-05-21 10:11 UTC, ngljcb commented
si, ho controllato, le domande sono quelli del corso, e le risposte sono corrette.. possiamo procedere

2024-05-21 10:11 UTC, merged