new notes
csunibo/strategia-aziendale pull request #17
Opened 2024-06-14 16:52 UTC by filippo-brigati

2024-06-14 17:06 UTC, foxyseta requested changes
Grazie mille! Abbiamo avuto problemi di conversione automatica da `.docx` a `.pdf` in passato quindi se dopo che ti abbiamo accettato la PR ci sono problemi facci sapere!

2024-06-14 17:06 UTC, foxyseta commented on .DS_Store
Questo lo cancellerei...

2024-06-15 16:35 UTC, filippo-brigati commented on .DS_Store
Ok grazie, non mi faceva modificare direttamente da qua (probabilmente sto sbagliando qualcosa io), ho aperto una nuova pr

2024-06-15 22:25 UTC, foxyseta commented on .DS_Store
Nessun problema, ti ho accettato l'altra. Sono sicuro che appena prendi la mano con git/gith*b impari :))) grazie ancora!

2024-06-15 22:26 UTC, foxyseta commented
Closing as duplicate of #18

2024-06-15 22:26 UTC, closed without merging